# Generated by Django 2.1.7 on 2019-03-31 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('numGames', models.IntegerField(default=0)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='gameID',
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='game',
            name='storage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='minesweeper_app.Storage'),
            preserve_default=False,
        ),
    ]
