# Generated by Django 2.1.7 on 2019-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_app', '0003_auto_20190331_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
