# Generated by Django 2.1.7 on 2019-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_app', '0004_auto_20190331_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='id',
        ),
        migrations.AddField(
            model_name='square',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='square',
            name='key',
            field=models.CharField(default='notassigned', max_length=200, primary_key=True, serialize=False),
        ),
    ]
