# Generated by Django 2.1.7 on 2019-03-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_app', '0006_auto_20190331_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
